# Generated by Django 6.0 on 2026-01-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0004_person_user_alter_person_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
