# Generated by Django 6.0 on 2026-01-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0006_alter_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='time_spent',
            field=models.PositiveIntegerField(),
        ),
    ]
